language: en
pipeline: supervised_embeddings

policies:
  - name: MemoizationPolicy
    max_history: 3
    priority: 3
  - name: KerasPolicy
    max_history: 3
    epochs: 200
    validation_splits: 0.1
    random_seed: 1
  - name: TwoStageFallbackPolicy
    nlu_threshold: 0.3
    ambiguity_threshold: 0.1
    core_threshold: 0.3
    fallback_core_action_name: "action_default_fallback"
    fallback_nlu_action_name: "action_default_fallback"
    deny_suggestion_intent_name: "out_of_scope"
  - name: MappingPolicy
  - name: FormPolicy
